import { Upload, FileJson, AlertCircle } from 'lucide-react';
import { useState, useCallback } from 'react';
import type { FOEReport } from '../types/report';

interface ReportUploadProps {
  onReportLoaded: (report: FOEReport) => void;
}

export function ReportUpload({ onReportLoaded }: ReportUploadProps) {
  const [isDragging, setIsDragging] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const validateReport = (data: any): data is FOEReport => {
    // Basic validation - check for required top-level fields
    return (
      data &&
      typeof data === 'object' &&
      'version' in data &&
      'repository' in data &&
      'dimensions' in data &&
      'overallScore' in data
    );
  };

  const handleFile = useCallback((file: File) => {
    setError(null);

    if (!file.name.endsWith('.json')) {
      setError('Please upload a JSON file');
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const text = e.target?.result as string;
        const data = JSON.parse(text);

        if (!validateReport(data)) {
          setError('Invalid FOE report format. Please upload a valid report JSON file.');
          return;
        }

        onReportLoaded(data);
      } catch (err) {
        setError('Failed to parse JSON file. Please check the file format.');
      }
    };
    reader.readAsText(file);
  }, [onReportLoaded]);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);

    const file = e.dataTransfer.files[0];
    if (file) {
      handleFile(file);
    }
  }, [handleFile]);

  const handleFileInput = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      handleFile(file);
    }
  }, [handleFile]);

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-50 dark:bg-gray-900 p-4">
      <div className="w-full max-w-2xl">
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-2">
            FOE Report Viewer
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Upload a Flow Optimized Engineering scan report to visualize results
          </p>
        </div>

        <div
          onDragOver={(e) => {
            e.preventDefault();
            setIsDragging(true);
          }}
          onDragLeave={() => setIsDragging(false)}
          onDrop={handleDrop}
          className={`relative border-2 border-dashed rounded-lg p-12 transition-colors ${
            isDragging
              ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20'
              : 'border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800'
          }`}
        >
          <input
            type="file"
            accept=".json"
            onChange={handleFileInput}
            className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
          />

          <div className="flex flex-col items-center text-center">
            {isDragging ? (
              <Upload className="w-16 h-16 text-blue-500 mb-4 animate-bounce" />
            ) : (
              <FileJson className="w-16 h-16 text-gray-400 dark:text-gray-500 mb-4" />
            )}

            <p className="text-lg font-medium text-gray-900 dark:text-white mb-2">
              {isDragging ? 'Drop your report here' : 'Drop your FOE report here'}
            </p>
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
              or click to browse files
            </p>
            <p className="text-xs text-gray-500 dark:text-gray-500">
              Accepts JSON files generated by the FOE scanner
            </p>
          </div>
        </div>

        {error && (
          <div className="mt-4 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-400 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <p className="text-sm font-medium text-red-800 dark:text-red-200">
                Error loading report
              </p>
              <p className="text-sm text-red-700 dark:text-red-300 mt-1">{error}</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
