import { FileQuestion, Upload } from "lucide-react";

interface EmptyProjectStateProps {
  onUpload?: () => void;
}

export function EmptyProjectState({ onUpload }: EmptyProjectStateProps) {
  return (
    <div
      className="flex flex-col items-center justify-center py-16 px-4"
      data-testid="empty-project-state"
    >
      {/* Icon */}
      <div className="relative mb-6">
        <FileQuestion className="w-24 h-24 text-gray-300 dark:text-gray-600" />
        <Upload className="w-10 h-10 text-blue-500 dark:text-blue-400 absolute -bottom-2 -right-2" />
      </div>

      {/* Message */}
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
        No Projects Found
      </h3>
      <p className="text-gray-600 dark:text-gray-400 text-center max-w-md mb-6">
        Get started by uploading your first FOE scan report or triggering a new
        scan to see your project insights here.
      </p>

      {/* CTA Button */}
      {onUpload && (
        <button
          onClick={onUpload}
          className="
            flex items-center gap-2 px-6 py-3
            text-white bg-blue-600 hover:bg-blue-700
            dark:bg-blue-500 dark:hover:bg-blue-600
            rounded-lg font-medium
            transition-colors
            focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2
            dark:focus:ring-offset-gray-900
          "
        >
          <Upload className="w-5 h-5" />
          Upload Report
        </button>
      )}

      {/* Help Text */}
      <div className="mt-8 text-sm text-gray-500 dark:text-gray-400 text-center max-w-lg">
        <p className="mb-2">💡 <strong>Tip:</strong> You can also:</p>
        <ul className="list-disc list-inside space-y-1">
          <li>Trigger a new scan from a repository directory</li>
          <li>Load reports from the API if connected</li>
          <li>Upload JSON reports generated by the FOE scanner</li>
        </ul>
      </div>
    </div>
  );
}
